PUT http://localhost:3000/newGame?gameMode=1

###

PUT http://localhost:3000/move
Content-Type: application/json

{
  "gameId": "game5",
  "position": 5
}

###

PUT http://localhost:3000/move
Content-Type: application/json

{
  "gameId": "game5",
  "position": 2
}

### 

PUT http://localhost:3000/endGame
Content-Type: application/json

{
  "gameId": "game5"
}

